"""initial_schema

Revision ID: 8d6386aec3e2
Revises: 
Create Date: 2026-07-24 12:01:20.035175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6386aec3e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('target_gender', sa.String(), nullable=True),
    sa.Column('style_preference', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('photo_consent', sa.Boolean(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('photo_storage_key', sa.String(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('occasion_tag', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('formality', sa.String(), nullable=True),
    sa.Column('target_gender', sa.String(), nullable=True),
    sa.Column('fabric_type', sa.String(), nullable=True),
    sa.Column('fit_type', sa.String(), nullable=True),
    sa.Column('sleeve_length', sa.String(), nullable=True),
    sa.Column('formality_score', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('style_tags', sa.Text(), nullable=True),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_items_id'), 'clothing_items', ['id'], unique=False)
    op.create_table('outfit_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_item_ids', sa.Text(), nullable=False),
    sa.Column('liked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_feedback_id'), 'outfit_feedback', ['id'], unique=False)
    op.create_table('try_on_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outfit_items_json', sa.Text(), nullable=True),
    sa.Column('result_image_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=20), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_on_results_id'), 'try_on_results', ['id'], unique=False)
    op.create_index(op.f('ix_try_on_results_job_id'), 'try_on_results', ['job_id'], unique=True)
    op.create_table('try_on_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_try_on_usage_user_date')
    )
    op.create_index(op.f('ix_try_on_usage_id'), 'try_on_usage', ['id'], unique=False)
    op.create_table('calendar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('occasion_tag', sa.String(), nullable=True),
    sa.Column('locked_outfit_id', sa.Integer(), nullable=True),
    sa.Column('try_on_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['try_on_result_id'], ['try_on_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_entries_id'), 'calendar_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_entries_id'), table_name='calendar_entries')
    op.drop_table('calendar_entries')
    op.drop_index(op.f('ix_try_on_usage_id'), table_name='try_on_usage')
    op.drop_table('try_on_usage')
    op.drop_index(op.f('ix_try_on_results_job_id'), table_name='try_on_results')
    op.drop_index(op.f('ix_try_on_results_id'), table_name='try_on_results')
    op.drop_table('try_on_results')
    op.drop_index(op.f('ix_outfit_feedback_id'), table_name='outfit_feedback')
    op.drop_table('outfit_feedback')
    op.drop_index(op.f('ix_clothing_items_id'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
